synolia_admin_commands:
    resource: |
        alias: synolia.command
        templates: "@SyliusAdmin\\Crud"
        section: admin
        grid: synolia_admin_commands
        except: ['show']
        permission: true
        vars:
            index:
                icon: 'box'
    type: sylius.resource

synolia_admin_scheduled_commands:
    resource: |
        alias: synolia.scheduled_command
        templates: "@SyliusAdmin\\Crud"
        section: admin
        grid: synolia_admin_scheduled_commands
        except: ['update', 'show']
        permission: true
        vars:
            index:
                icon: 'box'
    type: sylius.resource

download_schedule_log_file:
    path: /scheduled-commands/download/logfile/{command}
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\DownloadController::downloadLogFile
        _sylius:
            permission: true

execute_immediate_schedule:
    path: /scheduled-commands/execute/immediate/{commandId}
    methods: [GET|PUT]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\ScheduledCommandExecuteImmediateController::executeImmediate
        _sylius:
            permission: true

sylius_admin_scheduler_empty_log_file:
    path: /scheduled-commands/{command}/clean-log
    methods: [PUT]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Action\CleanLogAction
        _sylius:
            permission: true

sylius_admin_scheduler_view_log_file:
    path: /scheduled-commands/{command}/view-log
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\LogViewerController::show
        _sylius:
            permission: true

sylius_admin_scheduler_get_log_file:
    path: /scheduled-commands/{command}/get-log.json
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\LogViewerController::getLogs
        _sylius:
            permission: true

sylius_admin_scheduler_emtpy_logs:
    path: /scheduled-commands/emtpy_logs
    methods: [GET|PUT]
    controller: Synolia\SyliusSchedulerCommandPlugin\Controller\EmptyLogsController::emptyLogs
    defaults:
        _sylius:
            permission: true
            repository:
                method: findById
                arguments: [$ids]
