sylius_admin_scheduled_command:
    resource: |
        alias: sylius.scheduled_command
        templates: SyliusAdminBundle:Crud
        section: admin
        grid: sylius_admin_scheduled_command
        except: ['show']
        vars:
            index:
                icon: 'box'
    type: sylius.resource
    prefix: /admin

download_schedule_log_file:
    path: /admin/scheduled-commands/download/logfile/{command}
    methods: [GET]
    defaults:
        _controller: Synolia\SchedulerCommandPlugin\Controller\DownloadController::downloadLogFile