sylius_admin_scheduled_command:
    resource: |
        alias: sylius.scheduled_command
        templates: SyliusAdminBundle:Crud
        section: admin
        grid: sylius_admin_scheduled_command
        except: ['show']
        vars:
            index:
                icon: 'box'
    type: sylius.resource

download_schedule_log_file:
    path: /scheduled-commands/download/logfile/{command}
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\DownloadController::downloadLogFile

execute_immediate_schedule:
    path: /scheduled-commands/execute/immediate/{command}
    methods: [GET|PUT]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\ScheduledCommandExecuteImmediateController::executeImmediate
