imports:
    - { resource: "@SchedulerCommandPlugin/Resources/config/resources.yaml" }
    - { resource: "@SchedulerCommandPlugin/Resources/config/grids.yaml" }
    - { resource: "@SchedulerCommandPlugin/Resources/config/services.yaml" }
