sylius_grid:
    grids:
        sylius_admin_scheduled_command:
            driver:
                options:
                    class: Synolia\SyliusSchedulerCommandPlugin\Entity\ScheduledCommand
            fields:
                name:
                    type: string
                    label: sylius.ui.scheduled_command.name
                command:
                    type: string
                    label: sylius.ui.scheduled_command.command
                cronExpression:
                    type: string
                    label: sylius.ui.scheduled_command.cron_expression
                humanReadableExpression:
                    type: scheduled_human_readable_expression
                    label: sylius.ui.scheduled_command.human_readable_expression
                    options:
                        template: '@SynoliaSyliusSchedulerCommandPlugin/Grid/Column/human_readable_expression.html.twig'
                lastExecution:
                    type: datetime
                    label: sylius.ui.scheduled_command.last_execution
                commandExecutionTime:
                    type: scheduled_command_execution_time
                    label: sylius.ui.scheduled_command.command_execution_time
                lastReturnCode:
                    type: string
                    label: sylius.ui.scheduled_command.last_return_code
                logFile:
                    type: scheduled_command_url
                    label: sylius.ui.scheduled_command.log_file
                    options:
                        template: '@SynoliaSyliusSchedulerCommandPlugin/Grid/Column/log_file.html.twig'
                priority:
                    type: string
                    label: sylius.ui.scheduled_command.priority
                enabled:
                    type: twig
                    label: sylius.ui.scheduled_command.enabled
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    emptyLogFile:
                        type: emptyLogFile
                        label: Empty log
                        options:
                            link:
                                route: sylius_admin_scheduler_empty_log_file
                                parameters:
                                    command: resource.id
                    execute:
                        type: schedule_command_execute_immediate
                        label: sylius.ui.scheduled_command.execute_immediate
                        options:
                            link:
                                route: execute_immediate_schedule
                                parameters:
                                    command: resource.id
    templates:
        action:
            emptyLogFile: "@SynoliaSyliusSchedulerCommandPlugin/Grid/Action/empty_log_file.html.twig"
            schedule_command_execute_immediate: "@SynoliaSyliusSchedulerCommandPlugin/Grid/Action/execute_immediate.html.twig"
