sylius_resource:
    resources:
        sylius.scheduled_command:
            driver: doctrine/orm
            classes:
                model: Synolia\SyliusSchedulerCommandPlugin\Entity\ScheduledCommand
                form: Synolia\SyliusSchedulerCommandPlugin\Form\ScheduledCommandType
                repository: Synolia\SyliusSchedulerCommandPlugin\Repository\ScheduledCommandRepository
