services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusSchedulerCommandPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,SchedulerCommandPlugin.php}'

    Synolia\SyliusSchedulerCommandPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Synolia\SyliusSchedulerCommandPlugin\Parser\CommandParser:
        arguments:
            $excludedNamespaces: ['_global']

    Synolia\SyliusSchedulerCommandPlugin\Command\SynoliaSchedulerRunCommand:
        $logsDir: '%kernel.logs_dir%'

    app.grid_field.scheduled_command.url:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandUrlType
        arguments:
            $logsDir: '%kernel.logs_dir%'
        tags:
            - { name: sylius.grid_field, type: scheduled_command_url }
    app.grid_field.scheduled_command.humanReadableExpression:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandHumanReadableExpressionType
        tags:
            - { name: sylius.grid_field, type: scheduled_human_readable_expression }
