services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logsDir: '%kernel.logs_dir%'
            $projectDir: '%kernel.project_dir%'

    _instanceof:
        Synolia\SyliusSchedulerCommandPlugin\Checker\IsDueCheckerInterface:
            tags:
                - { name: !php/const Synolia\SyliusSchedulerCommandPlugin\Checker\IsDueCheckerInterface::TAG_ID }

    Synolia\SyliusSchedulerCommandPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,SynoliaSyliusSchedulerCommandPlugin.php}'

    Synolia\SyliusSchedulerCommandPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Synolia\SyliusSchedulerCommandPlugin\Parser\CommandParser:
        arguments:
            $excludedNamespaces: ['_global']

    app.grid_field.scheduled_command.url:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandUrlType
        tags:
            - { name: sylius.grid_field, type: scheduled_command_url }

    app.grid_field.scheduled_command.state:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandStateType
        tags:
            - { name: sylius.grid_field, type: scheduled_command_state }

    app.grid_field.scheduled_command.humanReadableExpression:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandHumanReadableExpressionType
        tags:
            - { name: sylius.grid_field, type: scheduled_human_readable_expression }

    app.grid_field.scheduled_command.execution_time:
        class: Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\ScheduledCommandExecutionTimeType
        tags:
            - { name: sylius.grid_field, type: scheduled_command_execution_time }

    Synolia\SyliusSchedulerCommandPlugin\Grid\FieldType\DatetimeFieldType:
        decorates: 'sylius.grid_field.datetime'
        arguments:
            $dataExtractor: '@sylius.grid.data_extractor.property_access'
        tags:
            - { name: sylius.grid_field, type: scheduled_command_executed_at }

    Synolia\SyliusSchedulerCommandPlugin\Listener\Grid\GoToHistoryButtonGridListener:
        tags:
            - { name: kernel.event_listener, event: sylius.grid.synolia_admin_commands, method: onSyliusGridAdmin }

    Synolia\SyliusSchedulerCommandPlugin\Listener\Grid\GoToCommandsButtonGridListener:
        tags:
            - { name: kernel.event_listener, event: sylius.grid.synolia_admin_scheduled_commands, method: onSyliusGridAdmin }

    Synolia\SyliusSchedulerCommandPlugin\Voter\IsDueVoterInterface:
        class: Synolia\SyliusSchedulerCommandPlugin\Voter\IsDueVoter
        arguments:
            - !tagged_iterator { tag: !php/const Synolia\SyliusSchedulerCommandPlugin\Checker\IsDueCheckerInterface::TAG_ID }
