Synolia\SyliusSchedulerCommandPlugin\Entity\Command:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
        command:
            - NotBlank: ~
        cronExpression:
            - NotBlank: ~
            - Length:
                min: 9
        priority:
            - NotBlank: ~
            - PositiveOrZero: ~
